disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - class_delegate_protocol
  - force_try
  - next_force_cast
  - trailing_whitespace
  - function_body_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
